### ISSUE TITLE
Request: Allow single to multiple json merging

### ISSUE THREAD

**Issue by Nodachi216** [Mpstark/ModTek#66] opened 2018-06-08 22:38 UTC
Here's what I want to be able to do, take a single json (defined in the mod.json file) and apply its changes across all jsons of a particular type or location.

Practical usage example: Make a single json containing mech hardpoint data and apply it to all chassis files.

**Comment by CptMoore** [comment] 2018-06-09 00:56
I think that would work great with the json manipulation code currently in works (#40).

The json manipulations says what to change how inside a file (you can surgically change hardpoint data), and then you only need a wildcard to apply those to several files.

**Comment by Mpstark** [comment] 2018-06-11 23:24
This is definitely what @CptMoore is working on with the "Advanced Merge" feature. I'm not sure when it'll be included, but I definitely want "ModuleManager" type functionality available in ModTek.

**Comment by Mpstark** [comment] 2018-06-11 23:24
Closing as a duplicate of #40

**Closed by Mpstark** 2018-06-11 23:24 UTC
